axon:
  distributed:
    enabled: true
  serializer:
    general: jackson
hotel:
  booking:
    command:
      snapshot-trigger-threshold-room: 200
      snapshot-trigger-threshold-account: 200
      snapshot-trigger-threshold-payment: 200
server:
  port: 8081
  error:
    include-message: always
    include-exception: true
spring:
  application:
    name: axon-hotel-booking-command
springdoc:
  paths-to-exclude:
    - /member-capabilities/**
    - /spring-command-bus-connector/**