{
 "title": "Axon Server Dashboard",
 "description": "Dashboard for Axon Server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Axon Server",
    "query": {
     "query": "label_values(axon_ApplicationCommandQueue_size,instance)"
    }
   },
   { "name": "context", "label": "Context", "query": { "query": "label_values(context)" } }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "table-old",
   "description": "Cluster status - Instance is either UP or DOWN",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{instance=~\"$instance\"}"
    },
    {
     "expr": "system_cpu_usage{instance=~\"$instance\"}*100"
    },
    {
     "expr": "max by (instance)(jvm_memory_max_bytes{instance=~\"$instance\"}) - max by (instance)(jvm_memory_used_bytes{instance=~\"$instance\"})"
    },
    {
     "expr": "max by (instance) (process_uptime_seconds{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Error/Warnings",
   "type": "graph",
   "description": "Shows count of errors and warnings in Axon Server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "sum by (level) (increase(logback_events_total{level=\"error\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum by (level) (increase(logback_events_total{level=\"warn\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "CPU% Basic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{instance=~\"$instance\"}*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (job)(jvm_memory_max_bytes{instance=~\"$instance\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "max by (job)(jvm_memory_used_bytes{instance=~\"$instance\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "max by (job)(jvm_memory_max_bytes{instance=~\"$instance\"}) - max by (job)(jvm_memory_used_bytes{instance=~\"$instance\"})",
     "legendFormat": "Avaliable"
    },
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg( process_uptime_seconds{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "table-old",
   "description": "Metric available in Axon Server 4.5+",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 18 },
   "targets": [
    {
     "expr": "disk_total_bytes{instance=~'$instance'}-0"
    },
    {
     "expr": "disk_free_bytes {instance=~'$instance'}-0"
    },
    {
     "expr": "predict_linear(disk_free_bytes{instance=~'$instance'}[24h], 24 * 3600)-0"
    },
    {
     "expr": "(disk_total_bytes{instance=~'$instance'}-disk_free_bytes{instance=~'$instance'}) *100/(disk_total_bytes {instance=~'$instance'}+(disk_total_bytes{instance=~'$instance'}-disk_free_bytes{instance=~'$instance'}))"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(system_cpu_count{job=\"axonserver\"})"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(system_cpu_count{job=\"axon-framework\"})"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "# of Commands",
   "type": "stat",
   "description": "Counts the total number of commands processed since start",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(axon_command_count_total{instance=~\"$instance\"})",
     "legendFormat": "Today "
    },
    {}
   ]
  },
  {
   "title": "# of Events",
   "type": "stat",
   "description": "Counts the total number of events processed since start",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(axon_event_count_total{instance=~\"$instance\"})",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "# of Snapshots",
   "type": "stat",
   "description": "Counts the total number of snapshots processed since start",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(axon_snapshot_count_total{instance=~\"$instance\"})",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "# of Queries",
   "type": "stat",
   "description": "Counts the total number of queries processed since the start",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(axon_query_count_total{instance=~\"$instance\"})",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "# of Subscription queries",
   "type": "stat",
   "description": "Total number of subscription queries since the start",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(axon_GlobalSubscriptionMetricRegistry_total{instance=~\"$instance\"})",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "# of  Active Commands",
   "type": "stat",
   "description": "Number of pending commands waiting to be completed",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(axon_commands_active{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Last token of Events",
   "type": "stat",
   "description": "Last  event token processed",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(axon_event_lastToken{instance=~\"$instance\",context=~\"$context\"})",
     "legendFormat": "Today "
    },
    {}
   ]
  },
  {
   "title": "Last token of Snapshots",
   "type": "stat",
   "description": "Last  snapshot token processed",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(axon_snapshot_lastToken{instance=~\"$instance\",context=~\"$context\"})",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "# of Active Queries",
   "type": "stat",
   "description": "Number of pending queries. Queries waiting in the registry to be completed.",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(axon_queries_active{instance=~\"$instance\"})",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "# of Active subscription queries",
   "type": "stat",
   "description": "Total number of subscription queries currently active",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(axon_GlobalSubscriptionMetricRegistry_active{instance=~\"$instance\"})",
     "legendFormat": "Today "
    }
   ]
  },
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Registers the duration of a command in the registry.\nMeaning measures time that the command handler takes to execute.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (request) (rate(axon_commands_seconds_sum{instance=~\"$instance\", context=~\"$context\"}[30s]))/ sum by (request) (rate(axon_commands_seconds_count{instance=~\"$instance\", context=~\"$context\"}[30s]) )",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "description": "Command types per second",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "commands/sec" }
   ],
   "targets": [
    {
     "expr": "sum by (request) ((rate(axon_commands_seconds_count{instance=~\"$instance\",context=~\"$context\"}[30s])))",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Routing",
   "type": "graph",
   "description": "Routing by application instances",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Source / Target" }
   ],
   "targets": [
    {
     "expr": "sum by (source) (( rate(axon_commands_seconds{instance=~\"$instance\",context=~\"$context\"}[1m]) ))",
     "legendFormat": "Source: {{source}} "
    },
    {
     "expr": "sum by (target) (( rate( axon_commands_seconds{instance=~\"$instance\",context=~\"$context\"}[1m]) ))",
     "legendFormat": "Target: {{target}} "
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Registers the duration of a query in the registry.\nMeaning measures time that the query handler takes to execute.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "s", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (request) (rate(axon_queries_seconds_sum{instance=~\"$instance\", context=~\"$context\"}[30s]))/ sum by (request) (rate(axon_queries_seconds_count{instance=~\"$instance\", context=~\"$context\"}[30s]) )",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "description": "Query types per second",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short", "label": "queries/sec" }
   ],
   "targets": [
    {
     "expr": "sum by (request) ((rate(axon_queries_seconds_count{instance=~\"$instance\",context=~\"$context\"}[30s])))",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Routing",
   "type": "graph",
   "description": "Routing by application instances",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (source) (( rate(axon_queries_seconds{instance=~\"$instance\",context=~\"$context\"}[1m]) ))",
     "legendFormat": "Source: {{source}} "
    },
    {
     "expr": "sum by (target) (( rate( axon_queries_seconds{instance=~\"$instance\",context=~\"$context\"}[1m]) ))",
     "legendFormat": "Target: {{target}} "
    }
   ]
  },
  {
   "title": "Subscription Updates",
   "type": "graph",
   "description": "Queries: Total number of subscription queries subscribed per application\n\nUpdates: Total number of updates submitted on subscription queries per application\n\nActive: Active number of subscription queries on this node per application",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short", "label": "updates/sec" }
   ],
   "targets": [
    {
     "expr": "sum by (component) (rate(axon_ApplicationSubscriptionMetricRegistry_updates_total{instance=~\"$instance\", context=~\"$context\"}[30s]))",
     "legendFormat": "{{component}}"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Events",
   "type": "graph",
   "description": "Number of events stored per second",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short", "label": "events/sec" }
   ],
   "targets": [
    {
     "expr": "sum by (context) (rate(axon_event_count_total{instance=~\"$instance\", context=~\"$context\"}[30s]))",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "graph",
   "description": "Number of snapshots stored per second",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short", "label": "snapshots/sec" }
   ],
   "targets": [
    {
     "expr": "sum by (context) (rate(axon_snapshot_count_total{instance=~\"$instance\", context=~\"$context\"}[30s]))",
     "legendFormat": "{{context}}"
    },
    {}
   ]
  },
  {
   "title": "Last token",
   "type": "graph",
   "description": "The last token processed for context",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max by (instance,context) ((axon_event_lastToken{instance=~\"$instance\", context=~\"$context\"}))",
     "legendFormat": " {{context}}@{{instance}}"
    },
    {}
   ]
  },
  { "title": "GRPC Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "# of Request",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (delta(grpc_io_server_request_count_cumulative_count{instance=~\"$instance\"}[1m])) ",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(grpc_io_client_error_count_cumulative{instance=~\"$instance\"}) / sum(grpc_io_client_finished_count_cumulative{instance=~\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "95% Percentile Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_server_latency_cumulative_bucket{instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "Avg Response Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg ((rate(grpc_io_client_response_bytes_cumulative_sum{instance=~\"$instance\"}[1m])/rate(grpc_io_client_response_bytes_cumulative_count{instance=~\"$instance\"}[1m])) > 0)",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "Avg Request Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg ((rate(grpc_io_client_request_bytes_cumulative_sum{instance=~\"$instance\"}[1m])/rate(grpc_io_client_request_bytes_cumulative_count{instance=~\"$instance\"}[1m])) > 0)",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "Overall Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(opencensus_io_http_server_latency_bucket{instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_server_latency_cumulative_bucket{instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_server_server_latency_cumulative_bucket{instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "99 percentile"
    }
   ]
  },
  {
   "title": "95th percentile Latency By gRPC Method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_cumulative_bucket{instance=~\"$instance\"}[5m])) by (le,method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Average Latency By GRPC Method",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg (rate(grpc_io_client_roundtrip_latency_cumulative_sum{instance=~\"$instance\"}[5m])/rate(grpc_io_client_roundtrip_latency_cumulative_count{instance=~\"$instance\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Client Request Count GRPC Method",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 150 },
   "yaxes": [
    { "format": "short", "label": "Client requests/sec" }
   ],
   "targets": [
    {
     "expr": "avg (rate(grpc_io_client_request_count_cumulative_sum{instance=~\"$instance\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Server Response Count GRPC Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 157 },
   "yaxes": [
    { "format": "short", "label": "requests/sec" }
   ],
   "targets": [
    {
     "expr": "avg (rate(grpc_io_server_response_count_cumulative_sum{instance=~\"$instance\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request and Response Bandwidth",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 165 },
   "yaxes": [
    { "format": "bytes", "label": "bandwidth/sec" }
   ],
   "targets": [
    {
     "expr": "avg by (job) (rate(grpc_io_server_request_bytes_cumulative_sum{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Request"
    },
    {
     "expr": "avg by (job) (rate(grpc_io_server_response_count_cumulative_sum{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Response"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "gauge",
   "description": "Number of error response by status since the start",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 165 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (canonical_status) (grpc_io_server_error_count_cumulative{instance=~\"$instance\"})",
     "legendFormat": "{{canonical_status}}"
    }
   ]
  },
  {
   "title": "Elections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 175 },
   "yaxes": [
    { "format": "short", "label": "election request/sec" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,method) (rate(grpc_io_server_request_count_cumulative_count{instance=~\"$instance\",method=~\"io.axoniq.axonserver.grpc.cluster.LeaderElectionService.*\"}[5m]))",
     "legendFormat": "{{method}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Methods Started/Finished",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 183 },
   "yaxes": [
    { "format": "percent", "label": "Started% - Finished%" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(grpc_io_server_started_count_cumulative{instance=~\"$instance\"}[30s]))",
     "legendFormat": "Started: {{method}}"
    },
    {
     "expr": "sum by (method) (rate(grpc_io_server_finished_count_cumulative{instance=~\"$instance\"}[30s]))",
     "legendFormat": "Finished: {{method}}"
    }
   ]
  }
 ]
}