axon:
  serializer:
    general: jackson
hotel:
  booking:
    command:
      snapshot-trigger-threshold-room: 200
      snapshot-trigger-threshold-account: 200
      snapshot-trigger-threshold-payment: 200
server:
  port: 8080
spring:
  application:
    name: axon-hotel-booking
  data:
    mongodb:
      uri: mongodb://mongo:1@localhost:27017/hotel-booking
      uuid-representation: standard