axon:
  serializer:
    general: jackson
hotel:
  booking:
    command:
      snapshot-trigger-threshold-room: 200
      snapshot-trigger-threshold-account: 200
      snapshot-trigger-threshold-payment: 200
server:
  port: 8080
  error:
    include-message: always
    include-exception: true
spring:
  application:
    name: axon-hotel-booking
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hotel-booking
      username: mongo
      password: "1"
      uuid-representation: standard