services:
  axonserver:
    image: axoniq/axonserver:4.6.1-jdk-17-dev
    hostname: axonserver
    volumes:
      - ./docker/axonserver:/config:ro
    ports:
      - "8024:8024"
      - "8124:8124"
      - "8224:8224"
    networks:
      - axon-net
  consul:
    image: bitnami/consul:1
    hostname: consul
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    networks:
      - axon-net
  prometheus:
    image: bitnami/prometheus:2
    hostname: prometheus
    user: "root"
    depends_on:
      - consul
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./docker/prometheus/data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - axon-net
  grafana:
    image: bitnami/grafana:9
    hostname: grafana
    depends_on:
      - prometheus
    volumes:
      - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    ports:
      - "3000:3000"
    networks:
      - axon-net
    environment:
      GF_SECURITY_ADMIN_PASSWORD: bitnami
  mongodb-hotel-booking-1:
    image: bitnami/mongodb:5.0
    ports:
      - "27017:27017"
    networks:
      - axon-net
    environment:
      MONGODB_ROOT_PASSWORD: 1
      MONGODB_DATABASE: hotel-booking
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: 1
  mongodb-hotel-booking-2:
    image: bitnami/mongodb:5.0
    profiles: [ "2-instances", "3-instances" ]
    ports:
      - "27018:27017"
    networks:
      - axon-net
    environment:
      MONGODB_ROOT_PASSWORD: 1
      MONGODB_DATABASE: hotel-booking
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: 1
  mongodb-hotel-booking-3:
    image: bitnami/mongodb:5.0
    profiles: [ "3-instances" ]
    ports:
      - "27019:27017"
    networks:
      - axon-net
    environment:
      MONGODB_ROOT_PASSWORD: 1
      MONGODB_DATABASE: hotel-booking
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: 1
networks:
  axon-net:
