services:
  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    volumes:
      - ./axonserver-config:/config:ro
    ports:
      - "8024:8024"
      - "8124:8124"
      - "8224:8224"
    networks:
      - axon-net
  consul:
    image: bitnami/consul:1.12.2
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    networks:
      - axon-net
  mongodb-hotel-booking:
    image: bitnami/mongodb:5.0
    ports:
      - "27017:27017"
    networks:
      - axon-net
    environment:
      MONGODB_ROOT_PASSWORD: 1
      MONGODB_DATABASE: hotel-booking
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: 1
volumes:
  axonserver-data:
networks:
  axon-net:
