axon:
  serializer:
    general: jackson
  metrics:
    auto-configuration:
      enabled: true
    micrometer:
      dimensional: true
server:
  port: 8181
  error:
    include-message: always
    include-exception: true
spring:
  application:
    name: axon-hotel-booking-query
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hotel-booking
      username: mongo
      password: "1"
      uuid-representation: standard
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true