axon:
  serializer:
    general: jackson
server:
  port: 8181
  error:
    include-message: always
    include-exception: true
spring:
  application:
    name: axon-hotel-booking-query
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hotel-booking
      username: mongo
      password: "1"
      uuid-representation: standard