axon:
  serializer:
    events: jackson
hotel:
  command:
    snapshot-trigger-threshold-room: 200
    snapshot-trigger-threshold-account: 200
    snapshot-trigger-threshold-payment: 200
spring:
  data:
    mongodb:
      uri: mongodb://mongo:1@localhost:27017/hotel